# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _                 
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                 /____/        
#
# Title of your website
title: "Feeling Responsive"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "A Flexible Theme for Jekyll"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "»Feeling Responsive« is a responsive theme for Jekyll based on the fabulous foundation framework with beautiful typography and a bright color palette."


# This URL is the main adresse. Don't include a slash at the end.
#
url: "http://phlow.github.io/feeling-responsive"
baseurl: ""

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash.
#
# Example: <img src="{{ site.urlimg }}/{{ post.image.title }}">
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}/image.jpg)
#
urlimg: "http://phlow.github.io/feeling-responsive/images/"


# Logo size is 600x80 pixels
logo: "logo.png"


# Paginates all X entries
paginate: 5


# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: "\n\n"
exclude: []
include: ['.htaccess']


# The language setting is used in /includes/header.html for html-settings
language: "en"


#
#       ____       ____            ____ 
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_  
#   /_____/\___/_/  \__,_/\__,_/_/\__/  
#                                       
# Default Settings

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: true 	# Show metadata beneath all pages
      sidebar: "" 		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: "your_author_name"
  -
    scope:
      path: ""        
      type: "posts"
    values:
      show_meta: true   # Show metadata beneath all posts
      sidebar: ""     # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: "your_author_name"



#       _   __            _             __  _           
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____ 
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/ 
#                       /____/                          
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________ 
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ / 
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_author:             "https://plus.google.com/u/0/118311555303973066167"
google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
bing_webmastertools_id:    "0FB4C028ABCF07C908C54386ABD2D97F"
alexa_verify_id:         "m1VxsMv1gIN-up4Sw0PGQIvyCRw"



#       ______            _                      
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  ) 
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicons, Apple Touch Buttons
#                                                 More information » http://j.mp/apple-touch-icons

favicon:                         "/assets/img/favicon-32x.png"                    # iOS7 Size 32x32
apple_touch_icon_iphone:         "/assets/img/touch-icon-iphone-60x.png"          # iOS7 Size 60x60
apple_touch_icon_iphone_retina:  "/assets/img/touch-icon-iphone-retina-120x.png"  # iOS7 Size 120x120
apple_touch_icon_ipad:           "/assets/img/touch-icon-ipad-76x.png"            # iOS7 Size 76x76
apple_touch_icon_ipad_retina:    "/assets/img/touch-icon-ipad-retina-152x.png"    # iOS7 Size 152x152
apple_touch_icon_precomposed:    "/assets/img/touch-icon-android-152x.png"        # iOS7 Size 152x152
msapplication_tileimage:         "/assets/img/windows-8-tile-icon-144x.png"       # Windows 8 Tile 144x144
msapplication_tilecolor:         "#334D5C"                                    # Windows 8 Tile Backgroundcolor


#       ______                __                __  
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<   
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

og_image:                           "http://images.phlow.de/phlow/phlow_de-logo-512x.png"
og_locale:                          "en_EN"
og_type:                            "website"
og_title:                           "Feeling Responsive – A Responsive Theme for Jekyll"
og_description:                     "Feeling Responsive is built on the fabulous Foundation Framework and comes with lots of features to show your content right."
# og_url:                           ""
# og_site_name:                     ""


#      _____            _       __   __  ___         ___      
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ / 
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/  
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#


#        ____  _                      
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  ) 
#    /_____/_/____/\__, /\__,_/____/  
#                    /_/              
#
# used in _includes/comments.html

disqus_shortname: feelingresponsive


#      _____                
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/ 
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#                           

sass:
    sass_dir: _sass
    style: :compressed


#       ___                __      __  _          
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  ) 
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/                   
#
# used in _includes/footer_scripts.html

google_analytics_tracking_id: UA-60112281-1

